version: '2'

services:
  db:
    image: postgres:13
    container_name: odoo_db
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myodoo
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always

  web:
    image: odoo:15
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8027:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - ./addons:/mnt/extra-addons
    restart: always
